package ca.mcmaster.se2aa4.island.teamXXX.Enums;

public enum Biome {
    // COMON 
    OCEAN, LAKE, BEACH, GRASSLAND, 

    // TROPICAL
    MANGROVE, TROPICAL_RAIN_FOREST, TROPICAL_SEASONAL_FOREST,

    // TEMPEATE
    TEMPERATE_DECIDUOUS_FOREST, TEMPERATE_RAIN_FOREST, TEMPERATE_DESERT,

    // NORDIC
    TAIGA, SNOW, TUNDRA, ALPINE, GLACIER,

    // SUBTROPICAL
    SHRUBLAND, SUB_TROPICAL_DESERT
}
